/*global Config, _ , URI, console*/
var GEOSERVER = "http://geoserver.nescaum-ccsc-dataservices.com/geoserver";
var API_SERVER = "http://api.nescaum-ccsc-dataservices.com/";

var CDN = function (url_str) {
  var url;
  if (Config.skip_cdn) {
    url = url_str;
  } else {
    var uri = new URI(url_str);
    var hostname = uri.hostname();

    if (hostname.match(/geoserver.nescaum-ccsc-dataservices.com/)) {
      uri.hostname("d3dfsz5phlpu8l.cloudfront.net");
      uri.port(null);
      uri.scheme("https");
    } else if (hostname.match(/api.nescaum-ccsc-dataservices.com/)) {
      uri.hostname("d2749s27r5h52i.cloudfront.net");
      uri.port(null);
      uri.scheme("https");
    } else {
      console.warn("Hostname not in a CDN", hostname);
    }

    url = uri.toString();
  }
  return url;
};

var available_layers = [
  {
    "id": "boundary_counties",
    "folder": "Boundaries",
    "name": "Counties",
    "sectors": []
  },
  {
    "id": "boundary_huc8",
    "folder": "Boundaries",
    "name": "Watersheds",
    "sectors": [],
  },
  {
    "id": "ma_historical_temperature",
    "folder": "Under Construction",
    "name": "MA Historical Temperatures",
    "sectors": ['testing'],
  },
  {
    "id": "ma_projected_temperature",
    "folder": "Under Construction",
    "name": "MA Projected Temperatures",
    "sectors": ['testing'],
  },
  {
    "id": "ma_projected_degree_days",
    "folder": "Under Construction",
    "name": "MA Projected Degree Days",
    "sectors": ['testing'],
  },
  {
    "id": "ma_historical_degree_days",
    "folder": "Under Construction",
    "name": "MA Historical Degree Days",
    "sectors": ['testing'],
  },
  {
    "id": "ma_historical_days_below_temp",
    "folder": "Under Construction",
    "name": "MA Historical Days Below Temperature Thresholds",
    "sectors": ['testing'],
  },
  {
    "id": "ma_projected_days_below_temp",
    "folder": "Under Construction",
    "name": "MA Projected Days Below Temperature Thresholds",
    "sectors": ['testing'],
  },
  {
    "id": "ma_historical_days_above_temp",
    "folder": "Under Construction",
    "name": "MA Historical Days Above Temperature Thresholds",
    "sectors": ['testing'],
  },
  {
    "id": "ma_projected_days_above_temp",
    "folder": "Under Construction",
    "name": "MA Projected Days Above Temperature Thresholds",
    "sectors": ['testing'],
  },
/*  {
    "id": "nfhl",
    "folder": "Public safety/emergency response",
    "name": "National Flood Hazard Layer",
    "description": "FEMA National Flood Hazard Layer",
    "source": "FEMA",
    "source_url": "http:\/\/www.fema.gov\/",
    "sectors": ["Water Resources"],
    "download_url": "http:\/\/www.hazards.fema.gov\/gis\/nfhl\/rest\/services\/public\/NFHL\/MapServer",
    "metadata_url": "http:\/\/www.hazards.fema.gov\/gis\/nfhl\/rest\/services\/public\/NFHL\/MapServer",
  },*/
  {
    "id": "noaa_slr",
    "folder": "Coastal Zones",
    "name": "Sea Level Rise (NOAA)",
    "description": "Sea Level Rise: the maps show inland extent and relative depth of inundation from 0 to 6 feet above mean higher high water (MHHW). Areas that are hydrologically connected (according to the digital elevation model used) are shown in shades of blue. Low-lying areas, displayed in green, are considered hydrologically “unconnected” areas that may flood. The inundation maps are created by subtracting the NOAA VDATUM MHHW surface from the digital elevation model. Mapping Confidence: blue areas denote a high confidence of inundation, orange areas denote a low confidence of inundation, and unshaded areas denote a high confidence that these areas will be dry given the chosen water level.",
    "source": "NOAA",
    "source_url": "https://coast.noaa.gov/slr",
    "sectors": [""],
    "download_url": null,
    "metadata_url": "https://coast.noaa.gov/digitalcoast/tools/slr",
  },
  {
    "id": "acec",
    "folder": "Natural Resources/Habitats",
    "name": "Areas of Critical Environmental Concern",
    "description": "The Areas of Critical Environmental Concern (ACEC) datalayers provide digital polygon and line boundaries for areas that have been designated ACECs by the Secretary of Energy and Environmental Affairs (EEA).  ACECs are places in Massachusetts that receive special recognition because of the quality, uniqueness and significance of their natural and cultural resources.  These areas are identified and nominated at the community level and are reviewed and designated by the state’s EEA Secretary.  ACEC designation creates a framework for local and regional stewardship of these critical resource areas and ecosystems.  ACEC designation also requires stricter environmental review of certain kinds of proposed development under state jurisdiction within the ACEC boundaries.",
    "source": "Department of Conservation and Recreation",
    "source_url": "http://www.mass.gov/eea/agencies/dcr/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/acecs.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/acecs.html",
  },
  {
    "id": "barrier_beaches",
    "folder": "Coastal Zones",
    "name": "Barrier Beaches",
    "description": "The state barrier beach data layer was compiled by the Resource Mapping Project staff at the University of Massachusetts, Amherst for the Massachusetts Coastal Zone Management Program.",
    "source": "Massachusetts Coastal Zone Management Program",
    "source_url": "http://www.mass.gov/eea/agencies/czm/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/barrb.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/state-designated-barrier-beaches-.html",
  },
  {
    "id": "dams",
    "folder": "Public Safety/Emergency Response",
    "name": "Dams",
    "description": "The Massachusetts Dams data layer contains points derived from a dam safety database maintained by the Massachusetts Office of Dam Safety (ODS). The ODS database includes detailed information about each dam for operational purposes.  Most of the location information was derived from historic data and has been ground-truthed against inspection and ownership reports that are maintained by the ODS. The locations of some dams have not been confirmed. These are pending verification and can be identified through the field 'LocStatus.' Dams regulated by the ODS in accordance with regulation CMR 302 10.00 are listed as 'Office of Dam Safety' in the field 'RegAuth'. Please report any data errors or inconsistencies to the Office of Dam Safety (dam.safety@state.ma.us) or DCR-GIS (chandreyee.lahiri@state.ma.us)",
    "source": "Massachusetts Office of Dam Safety",
    "source_url": "http://www.mass.gov/eea/agencies/dcr/conservation/dam-safety/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/dams.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/dams.html",
  },
  {
    "id": "groundwater_discharge",
    "folder": "Water Resources",
    "name": "Groundwater Discharge",
    "description": "The Massachusetts Department of Environmental Protection (MassDEP) Bureau of Water Resources (BWR), Wastewater Management Program is responsible for regulating the discharge of pollutants to the groundwaters of The Commonwealth (314 CMR 5.00). See the MassDEP Groundwater Discharge Permitting website for details.",
    "source": "MassDEP",
    "source_url": "http://www.mass.gov/eea/agencies/massdep/water/wastewater/groundwater-discharge-permitting.html",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/gwp.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/gwp.html",
  },
  {
    "id": "public_water_supplies",
    "folder": "Water Resources",
    "name": "Public Water Supplies",
    "description": "The Public Water Supply (PWS) datalayer contains the locations of public community surface and groundwater supply sources and public non-community supply sources as defined in 310 CMR 22.00. The public water supply systems represented in this datalayer are based primarily on information in the DEP’s Water Quality Testing System (WQTS) database. The WQTS database is the Department’s central database for tracking water supply data. The PWS datalayer also contains the locations of proposed wells that have a defined DEP approved wellhead protection area (Zone IIs).",
    "source": "MassDEP",
    "source_url": "http://www.mass.gov/eea/agencies/massdep/water/wastewater/groundwater-discharge-permitting.html",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/order-restricted-data.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/pws.html",
  },
  {
    "id": "wellhead_protection",
    "folder": "Water Resources",
    "name": "Wellhead Protection Areas",
    "description": "Wellhead protection areas are important for protecting the recharge area around public water supply (PWS) groundwater sources. A Zone II is a wellhead protection area that has been determined by hydro-geologic modeling and approved by the Department of Environmental Protection’s (DEP) Drinking Water Program (DWP). In cases where hydro-geologic modeling studies have not been performed and there is no approved Zone II, an Interim Wellhead Protection Area (IWPA) is established based on DEP DWP well pumping rates or default values. Certain land uses may be either prohibited or restricted in both approved (Zone II) and interim (IWPA) wellhead protection areas. For MassDEP's regulatory wording of these zones please see Water Supply Protection Area Definitions.",
    "source": "MassDEP Drinking Water Program Drinking Water Program",
    "source_url": "http://www.mass.gov/dep/water/drinking.htm",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/zone2_zone1_iwpa.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/dep-wellhead-protection-areas-zone-ii-iwpa.html",
  },
  {
    "id": "outstanding_resource_waters",
    "folder": "Water Resources",
    "name": "Outstanding Resource Waters",
    "description": "This datalayer delineates  areas in which certain waters are afforded Outstanding Resource Water (ORW) protection under the Massachusetts Surface Water Quality Standards, 314 CMR 4.00 (WQS). According to 314 CMR 4.04(3): Certain waters are designated for protection under this provision in 314 CMR 4.06. These waters include Class A Public Water Supplies (314 CMR 4.06(1)(d)1.) and their tributaries, certain wetlands as specified in 314 CMR 4.06(2) and other waters as determined by the Department based on their outstanding socio-economic, recreational, ecological and/or aesthetic values. The quality of these waters shall be protected and maintained. It is important to note first, that the areas delineated in this datalayer are not themselves ORWs, and, second, that only certain waters within the delineated areas are ORWs. Additionally, while the WQS designate Massachusetts Division of Fisheries and Wildlife as ORWs, certified vernal pools are NOT included in this datalayer (see 314 CMR 4.06(2)). Further, there may be areas not shown in this datalayer that contain ORWs.",
    "source": "MassDEP",
    "source_url": "http://www.mass.gov/dep/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/orw.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/orw.html",
  },
  {
    "id": "electric_providers",
    "folder": "Energy",
    "name": "Electricity Providers",
    "description": "This table contains the public Electric, Natural Gas, and Cable Television utility providers for each Massachusetts municipality. The source of data for Electric and Natural Gas was the Massachusetts Department of Public Utilities, September 2015. The source of data for Cable utilities was the Massachusetts Department of Telecommunications and Cable, June 2015. In addition, a field also stores information on whether a community provides its own Internet service (source: Northeast Public Power Association, July 2015).",
    "source": "Massachusetts Department of Public Utilities",
    "source_url": "http://www.mass.gov/eea/grants-and-tech-assistance/guidance-technical-assistance/agencies-and-divisions/dpu/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/pubutil.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/pubutil.html",
  },
  {
    "id": "gas_providers",
    "folder": "Energy",
    "name": "Natural Gas Providers",
    "description": "This table contains the public Electric, Natural Gas, and Cable Television utility providers for each Massachusetts municipality. The source of data for Electric and Natural Gas was the Massachusetts Department of Public Utilities, September 2015. The source of data for Cable utilities was the Massachusetts Department of Telecommunications and Cable, June 2015. In addition, a field also stores information on whether a community provides its own Internet service (source: Northeast Public Power Association, July 2015).",
    "source": "Massachusetts Department of Public Utilities",
    "source_url": "http://www.mass.gov/eea/grants-and-tech-assistance/guidance-technical-assistance/agencies-and-divisions/dpu/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/pubutil.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/pubutil.html",
  },
  {
    "id": "aquifers",
    "folder": "Water Resources",
    "name": "Aquifers",
    "description": "MassGIS produced an aquifer datalayer composed of 20 individual panels, generally based on the boundaries of the major drainage basins. Areas of high and medium yield were mapped. The SDE layers contain seamless data from Basin-based tiles pdf format of ix_bas.pdf and are named AQUIFERS_POLY and AQUIFERS_ARC.  Aquifer polygons were not delineated for Cape Cod and the Elizabeth Islands. These areas in their entirety are considered by the Massachusetts Contingency Plan (MCP) as medium yield aquifers. The areas of Martha's Vineyard and Nantucket not delineated as high yield aquifers are also considered as medium yield under the MCP.",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/aquifers.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/aquifers-.html",
  },
  {
    "id": "surface_water_protection",
    "folder": "Water Resources",
    "name": "Surface Water Protection",
    "description": "These Surface Water Supply Protection Areas delineate those areas included in 310 CMR 22.00, the Massachusetts Drinking Water Regulations, as Surface Water Supply Protection Zones: ZONEA: represents a) the land area between the surface water source and the upper boundary of the bank; b) the land area within a 400 foot lateral distance from the upper boundary of the bank of a Class A surface water source, as defined in 314 CMR 4.05(3)(a); and c) the land area within a 200 foot lateral distance from the upper boundary of the bank of a tributary or associated surface water body. ZONEB: represents the land area within one-half mile of the upper boundary of the bank of a Class A surface water source, as defined in 314 CMR 4.05(3)(a), or edge of watershed, whichever is less. Zone B always includes the land area within a 400 ft lateral distance from the upper boundary of the bank of a Class A surface water source. ZONEC: represents the land area not designated as Zone A or B within the watershed of a Class A surface water source, as defined in 314 CMR 4.05(3)(a).  All active and inactive surface water supplies have zones delineated, but some may be covered by other legislation. MassDEP protection Zones A, B, & C are in effect at MWRA sources and are subject to the protections in 310 CMR 22.00. MWRA has additional protections for their reservoirs that are included in the Massachusetts Watershed Protection Act, MGL 350 CMR 11.00. Watershed extents for all surface water supplies including active, inactive, emergency, sources outside of Massachusetts, watersheds that extend into other states and watersheds of sources from other states that extend into Massachusetts are included in the datalayer SWP Watersheds. Surface water intakes on Class B Rivers are not included in either datalayer. The reservoir features were taken from the datalayer and removed from the Zone A and B features and added as a separate feature. For MassDEP's regulatory wording of these zones please see Water Supply Protection Area Definitions..",
    "source": "Mass Department of Environmental Protection",
    "source_url": "http://www.mass.gov/dep",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/swp_zones.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/swp.html",
  },
  {
    "id": "transmission_lines",
    "folder": "Energy",
    "name": "Transmission Lines",
    "description": "The U.S. Geological Survey (USGS) distributes Digital Line Graphs (DLG) from its 1:100,000-scale maps showing pipelines, transmission lines, and other miscellaneous transportation features. MassGIS assembled these data into a statewide layer consisting of all the transportation features identified by USGS other than railroads and vehicle roadways and which appear on the 1:100,000 USGS quadrangle sheets.  Although the pipelines and transmission lines appear on maps, they are not necessarily in active use. The linework is generally excellent, although MassGIS has noted that some lines are discontinuous (not perfectly edgematched) at USGS 1:100,000 quadrangle boundaries. Railroad transportation features are included in the Trains layer.",
    "source": "U.S. Geological Survey",
    "source_url": "https://www.usgs.gov/",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/order-restricted-data.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/trnslns.html",
  },
  {
    "id": "impervious_surface",
    "folder": "Land Cover",
    "name": "Impervious Surfaces",
    "description": "The Impervious Surface raster layer represents impervious surfaces covering the Commonwealth of Massachusetts. The surfaces were extracted using semi-automated techniques by Sanborn Map Company from 50-cm Vexcel UltraCam near infrared orthoimagery that was acquired in April 2005 as part of the Color Ortho Imagery project. The pixel size for the impervious surface data is 1-meter.",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/ftpimpsurf.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/impervioussurface.html",
  },
  {
    "id": "dcr_roads_trails",
    "folder": "Recreation",
    "name": "DCR Roads and Trails",
    "description": "The Massachusetts Department of Conservation and Recreation (DCR) – Division of State Parks and Recreation (DSPR) Roads and Trails datalayer contains all legal roads and trails (lines and point features) identified by DCR staff and consultants on DCR DSPR properties (as well as some of the Urban Parks; eventually all trails on these properties will be integrated into this dataset). Roads and trails on private and non-DCR public land were mapped if they connected to these roads and trails and should be used with permission and should not be used if posted.",
    "source": "MA Department of Conservation and Recreation",
    "source_url": "http://www.mass.gov/eea/agencies/dcr/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/dcrtrails.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/dcrtrails.html",
  },
  {
    "id": "bicycle_trails",
    "folder": "Recreation",
    "name": "Bicycle Trails",
    "description": "This dataset, formerly named Rail Trails, was created by the Massachusetts Department of Conservation and Recreation (formerly DEM - Dept. of Environmental Management) for the purpose of regional planning and mapping. In 2002 the layer was updated and renamed Bicycle Trails. The linework in this layer represents trails which all permit bicycle travel or corridors with conversion potential; however, bicycles are not the exclusive travel mode permitted on these trails. The manager or owner of the trail should be contacted for detailed information about the permitted uses and rules of conduct that are specific to that trail. Most such corridors use, or connect to, old railway lines. The trails represented in this layer are open to bicycling as well as some combination of activities such as walking, jogging, roller blading, skiing, horse riding, snowmobiling, etc, though there are many other trails in the state that are considered multi-use but which are not included in this layer.",
    "source": "MA Department of Conservation and Recreation",
    "source_url": "http://www.mass.gov/eea/agencies/dcr/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/biketrails_arc.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/bicycle-trails.html",
  },
  {
    "id": "wetlands",
    "folder": "Water Resources",
    "name": "MassDEP Wetlands",
    "description": " layer contains polygon features delineating mapped wetland resource areas and attribute codes indicating wetland type.",
    "source": "Mass Department of Environmental Protection",
    "source_url": "http://www.mass.gov/dep/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/wetlandsdep_poly.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/depwetlands112000.html",
  },
  {
    "id": "fire_stations",
    "folder": "Public Safety/Emergency Response",
    "name": "Fire Stations",
    "description": "The Fire Stations layer shows the point locations of 789 Fire stations in the Commonwealth of Massachusetts. The Massachusetts Emergency Management Agency (MEMA) GIS Program in cooperation with the Regional Planning Agencies and participating communities created the data as part of the development of Homeland Security Data Layers.",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/firestations_pt.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/fire-stations-.html",
  },
  {
    "id": "police_stations",
    "folder": "Public Safety/Emergency Response",
    "name": "Police Stations",
    "description": "The Police Stations layer shows the point locations of law enforcement and sheriff offices in Massachusetts, covering local, county and state jurisdictions. The Massachusetts Emergency Management Agency (MEMA) GIS Program in cooperation with the Regional Planning Agencies and participating communities created the original data as part of the development of Homeland Security Data Layers. MassGIS has since incorporated updates into the data.",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/policestations.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/policestations.html",
  },
  {
    "id": "land_use",
    "folder": "Land Cover",
    "name": "Land Use 2005",
    "description": "The Impervious Surface raster layer represents impervious surfaces covering the Commonwealth of Massachusetts. The surfaces were extracted using semi-automated techniques by Sanborn Map Company from 50-cm Vexcel UltraCam near infrared orthoimagery that was acquired in April 2005 as part of the Color Ortho Imagery project. The pixel size for the impervious surface data is 1-meter.",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/ftplus2005.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/lus2005.html",
  },
  {
    "id": "openspace_owner",
    "folder": "Recreation",
    "name": "Open Space by Owner",
    "description": "The protected and recreational open space datalayer contains the boundaries of conservation lands and outdoor recreational facilities in Massachusetts. The associated database contains relevant information about each parcel, including ownership, level of protection, public accessibility, assessor’s map and lot numbers, and related legal interests held on the land, including conservation restrictions. Conservation and outdoor recreational facilities owned by federal, state, county, municipal, and nonprofit enterprises are included in this datalayer. Not all lands in this layer are protected in perpetuity, though nearly all have at least some level of protection.",
    "source": "Executive Office of Energy and Environmental Affairs",
    "source_url": "http://www.mass.gov/eea/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/open_spc/openspace.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/osp.html",
  },
/*  {
    "id": "openspace_type",
    "folder": "Recreation",
    "name": "Open Space by Type",
    "description": "The protected and recreational open space datalayer contains the boundaries of conservation lands and outdoor recreational facilities in Massachusetts. The associated database contains relevant information about each parcel, including ownership, level of protection, public accessibility, assessor’s map and lot numbers, and related legal interests held on the land, including conservation restrictions. Conservation and outdoor recreational facilities owned by federal, state, county, municipal, and nonprofit enterprises are included in this datalayer. Not all lands in this layer are protected in perpetuity, though nearly all have at least some level of protection.",
    "source": "Executive Office of Energy and Environmental Affairs",
    "source_url": "http://www.mass.gov/eea/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/open_spc/openspace.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/osp.html",
  },*/
  {
    "id": "biomap_core",
    "folder": "Natural Resources/Habitats",
    "name": "BioMAP2",
    "description": "The Massachusetts Natural Heritage & Endangered Species Program and The Nature Conservancy’s Massachusetts Program developed BioMap2 in 2010 as a conservation plan to protect the state’s biodiversity. BioMap2 is designed to guide strategic biodiversity conservation in Massachusetts over the next decade by focusing land protection and stewardship on the areas that are most critical for ensuring the long-term persistence of rare and other native species and their habitats, exemplary natural communities, and a diversity of ecosystems.",
    "source": "The Massachusetts Natural Heritage & Endangered Species Program",
    "source_url": "http://www.mass.gov/eea/agencies/dfg/dfw/natural-heritage/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/biomap2.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/biomap2.html",
  },
  {
    "id": "tax_parcels",
    "folder": "Boundaries",
    "name": "Tax Parcels",
    "description": "MassGIS' Level 3 Assessors’ Parcel Mapping data set, containing property (land lot) boundaries and database information from each community's assessor, was developed through a competitive procurement funded by MassGIS.  Each community in the Commonwealth was bid on by one or more vendors and the unit of work awarded was a city or town.  The specification for this work was Level 3 of the MassGIS Digital Parcel Standard.  As of October 30, 2013, standardization of assessor parcel mapping for 350 of Massachusetts' 351 cities and towns has been completed (data for Boston is not part of this project and will be processed separately). MassGIS is continuing the project, updating parcel data provided by municipalities.",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/l3parcels.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/l3parcels.html",
  },
  {
    "id": "boundary_state",
    "folder": "Boundaries",
    "name": "State",
    "description": "These polygon and line datalayers are available that represent the outline (boundary) of the Commonwealth of Massachusetts:",
    "source": "MassGIS",
    "source_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/outline25k.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/outline.html",
  },
  {
    "id": "flood_zones",
    "folder": "Public Safety/Emergency Response",
    "name": "Flood Zones",
    "description": "These data represent a subset of the data available on the paper Flood Insurance Rate Maps (FIRM) as provided by the Federal Emergency Management Agency (FEMA). The Q3 flood data were developed to support floodplain management and planning activities but do not replace the official paper FIRMs. These data are not suitable for engineering applications or site work nor can the data be used to determine absolute delineation of flood boundaries. Instead the data should be used to portray zones of uncertainty and possible risks associated with flooding. All counties except Franklin are available for Massachusetts.",
    "source": "FEMA",
    "source_url": "http://www.fema.gov/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/FEMA_Q3_Flood.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/q3.html",
  },
  {
    "id": "env_justice",
    "folder": "Demographics",
    "name": "Environmental Justice Populations",
    "description": "??",
    "source": "???",
    "source_url": "http://www.nrcs.usda.gov/",
    "sectors": [""],
    "download_url": "",
    "metadata_url": "",
  },
  {
    "id": "soils",
    "folder": "Land Cover",
    "name": "Soils",
    "description": "The Soils datalayer has been automated from published soils surveys as provided on various media by the United States Department of Agriculture (USDA) Natural Resources Conservation Service (NRCS). All soils data released by MassGIS have been SSURGO-certified, which means they have been reviewed and approved by the NRCS and meet all standards and requirements for inclusion in the national release of county-level digital soils data. Soil survey areas are roughly based on county boundaries. The SSURGO-certified soils dataset is generally the most detailed level of soil geographic data developed by the National Cooperative Soil Survey. The information was prepared by digitizing maps, by compiling information onto a planimetric correct base and digitizing, or by revising digitized maps using remotely sensed and other information. The data include a detailed, field verified inventory of soils and miscellaneous areas that normally occur in a repeatable pattern on the landscape and that can be cartographically shown at the scale mapped. Data for survey areas were developed using various scale base maps: some areas at a 1:25,000 or 1:12,000 scale, or at larger scales where source materials (e.g. 1:5,000 MassGIS ortho imagery) were available. Details for a specific survey area are provided in the NRCS-produced metadata that are distributed with the spatial data.  The soil map units are linked to attributes in the National Soil Information System (NASIS) relational database, which gives the proportionate extent of the component soils and their properties.",
    "source": "United States Department of Agriculture (USDA) Natural Resources Conservation Service ",
    "source_url": "http://www.nrcs.usda.gov/",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/ftpsoi.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/soi.html",
  },
  {
    "id": "hurricane_surge",
    "folder": "Coastal Zones",
    "name": "Hurricane Surge",
    "description": "The state barrier beach data layer was compiled by the Resource Mapping Project staff at the University of Massachusetts, Amherst for the Massachusetts Coastal Zone Management Program.",
    "source": "Massachusetts Coastal Zone Management Program",
    "source_url": "http://www.mass.gov/eea/agencies/czm/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/barrb.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/state-designated-barrier-beaches-.html",
  },
  {
    "id": "wind_power",
    "folder": "Energy",
    "name": "Wind Power Density at 50m",
    "description": "This data layer is a vector version of the AWS Truewind, LLC, Massachusetts Technology Collaborative 50 meter elevation wind power density raster layer. The raster layer work was jointly funded by the Connecticut Clean Energy Fund, the Massachusetts Technological Collaborative, and Northeast Utilities System.  The raster data were re-classified (AWS_CLASS) in accordance with the 8 classes used by Mass. Tech et al. The data were then converted from raster to polygon using the GRIDPOLY command. The PWRDENSITY field was created to show the power density range (watts/sq. meters) for each class. The data were then transformed from WGS1984 to NAD83 SPC using NAD1983toWGS1984 transform 5 (United States) and clipped to the extent of the WINDSPEEDGRID_POLY layer created by MassGIS and AWS Truewind, LLC. Processing of this polygon layer was completed by the Massachusetts Water Resources Authority (MWRA) GIS program and provided to MassGIS for distribution.",
    "source": "Massachusetts Technology Collaborative",
    "source_url": "http://www.masstech.org/",
    "sectors": [""],
    "download_url": "http://wsgw.mass.gov/data/gispub/shape/state/windpower.zip",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/wind-power-density-at-50m.html",
  },
  {
    "id": "prime_forest",
    "folder": "Agriculture/Forestry",
    "name": "Prime Forest Land",
    "description": "Using primarily the NRCS/MassGIS Soils data, the basic procedure was to classify potentially forested land into nine different categories based on potential average timber productivity of white pine and red oak “…per acre per year at culmination of mean annual increment. Site index values are at age 50.” Other data sets were used to refine this classification, including aspect, land cover, riparian, slope position, wetlands, hydrologic soil association and unique areas.  With the January 2013 update the dataset is complete statewide.",
    "source": "DCR, Bureau of Forestry, Management Forestry Program",
    "source_url": "http://www.mass.gov/eea/agencies/dcr/conservation/forestry-and-fire-control/forestry.html",
    "sectors": [""],
    "download_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/primeforest.html",
    "metadata_url": "http://www.mass.gov/anf/research-and-tech/it-serv-and-support/application-serv/office-of-geographic-information-massgis/datalayers/primeforest.html",
  },
  {
    "id": "tree_atlas",
    "folder": "Agriculture/Forestry",
    "name": "USFS Climate Change Atlas - Tree Species",
    "description": "Modeled importance value (IV) of 20 Massachusetts native tree species for three climate conditions: 1) current climate (1961-1990 average); 2) future climate (2071-2100 average) with IPCC scenario B1 (significant conservation and reduction of CO2 emissions); and 3) future climate (2071-2100 average) with IPCC scenario A1FI (high emissions, no modification in current emission trends). Importance Value measures the dominance of a tree species in a forest, based on the relative frequency, density, and basal area of the species. For more information on the models and to explore more tree species and climate scenarios, visit the US Forest Service Climate Change Atlas: http://www.fs.fed.us/nrs/atlas/",
    "source": "USDA Forest Service Northern Research Station",
    "source_url": "http:\/\/www.fs.fed.us\/nrs\/atlas\/",
    "sectors": [""],
    "download_url": null,
    "metadata_url": null,
  },

];

var desired_active_on_load = [

];
